### ISSUE TITLE
update to sigar 1.6.6

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [kamon-io/sigar-loader#1]
see https://github.com/akka/akka/pull/16475#issuecomment-67936820 ; @hepin1989 thank you

**Comment by Andrei-Pozolotin** [comment]
@ivantopo  @dpsoft  please release v 1.6.6 from branch `origin-hyperic`

**Comment by He-Pin** [comment]
I found it here.
http://maven.hyperic.org/
and the last version is 1.6.6.12.
and seems like we could find the repo here
https://github.com/hyperic/hq/blob/master/pom.xml

**Comment by dpsoft** [comment]
we released sigar-loader-1.6.6 with the sigar 1.6.6.12. version -> https://oss.sonatype.org/#nexus-search;quick~sigar-loader

**Comment by Andrei-Pozolotin** [comment]
thank you
