### ISSUE TITLE
library is not bundled with  libsigar-universal64-macosx.dylib

### ISSUE THREAD

**Issue by kuzkdmy** [kamon-io/sigar-loader#11]
<img width="1035" alt="default" src="https://user-images.githubusercontent.com/15995100/50227518-96c20000-03ae-11e9-9d3e-ed105a77c694.png">

**Comment by dpsoft** [comment]
@kuzkdmy please use: https://oss.sonatype.org/service/local/repositories/releases/content/io/kamon/sigar-loader/1.6.5-rev003/sigar-loader-1.6.5-rev003.jar

```xml
<dependency>
  <groupId>io.kamon</groupId>
  <artifactId>sigar-loader</artifactId>
  <version>1.6.5-rev003</version>
</dependency>
```

**Comment by kuzkdmy** [comment]
Many thanks.
